### ISSUE TITLE
Remove checkout step from Docker build action

### ISSUE THREAD

**Issue by okiedork** [package-health/php#113]
https://github.com/package-health/php/blob/851761de62076b1772602dd97f4ceab62b76350d/.github/workflows/build-docker-image.yml#L50-L51

As explained [here](https://github.com/docker/build-push-action#git-context), should we remove the checkout step?
> By default, this action uses the Git context so you don't need to use the actions/checkout action to check out the repository because this will be done directly by BuildKit.

**Comment by flavioheleno** [comment]
Well, if the action itself guarantees that it's using the git context, then I think we should follow their instructions and remove that step :-)

Great catch!
